#!/bin/bash
echo "=== UAM STATUS CHECK ==="
echo ""
echo "Run these commands on the router:"
echo ""
echo "1. Check UAM handler script exists:"
echo "   ls -la /usr/share/uspot/handler-uam.uc"
echo ""
echo "2. Check uhttpd UAM listener config:"
echo "   uci show uhttpd.uam3990"
echo ""
echo "3. Check uhttpd errors:"
echo "   logread | grep uhttpd | tail -20"
echo ""
echo "4. Check if UAM port is listening:"
echo "   netstat -tlnp | grep 3990"
echo ""
echo "5. Check uspot config:"
echo "   uci show uspot.hotspot | grep -E '(auth_mode|uam_server|uam_port)'"
