/**
 * Run Manual SQL Migrations
 * 
 * This script runs all manual SQL migration files in order.
 * These are migrations that can't be generated by Prisma (triggers, functions, partial indexes, etc.)
 * 
 * Usage:
 *   tsx packages/prisma/scripts/run-manual-migrations.ts
 */

import { PrismaClient } from '@prisma/client';
import { readFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const prisma = new PrismaClient();

// List of manual migration files in execution order
const MANUAL_MIGRATIONS = [
  '000_production_triggers.sql',
  '001_performance_indexes.sql',
  '002_materialized_view_daily_stats.sql',
  '003_router_daily_usage_triggers.sql',
  '004_partial_index_and_stoptime.sql', // New migration
];

async function runManualMigrations() {
  // Get migrations directory relative to this script
  const migrationsDir = join(__dirname, '..', 'migrations');
  
  console.log('🔧 Running manual SQL migrations...\n');

  for (const migrationFile of MANUAL_MIGRATIONS) {
    const filePath = join(migrationsDir, migrationFile);
    
    try {
      console.log(`📄 Executing: ${migrationFile}`);
      const sql = readFileSync(filePath, 'utf-8');
      
      // Execute SQL using Prisma's raw query
      await prisma.$executeRawUnsafe(sql);
      
      console.log(`✅ Completed: ${migrationFile}\n`);
    } catch (error: any) {
      // Check if it's a "already exists" error (idempotent)
      if (error.message?.includes('already exists') || 
          error.message?.includes('duplicate') ||
          error.code === '42P07' || // PostgreSQL: duplicate_table
          error.code === '42710') {  // PostgreSQL: duplicate_object
        console.log(`⏭️  Skipped (already applied): ${migrationFile}\n`);
      } else {
        console.error(`❌ Error executing ${migrationFile}:`, error.message);
        throw error;
      }
    }
  }

  console.log('✨ All manual migrations completed successfully!');
}

async function main() {
  try {
    await runManualMigrations();
  } catch (error) {
    console.error('❌ Migration failed:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();

