#!/bin/bash
#
# SpotFi OpenWRT Router Auto-Setup Script
# 
# This script automatically configures an OpenWRT router for SpotFi
# Run this script on the OpenWRT router via SSH
#
# Usage: ./openwrt-setup.sh ROUTER_ID TOKEN RADIUS_SECRET SERVER_IP MAC_ADDRESS
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
  echo -e "${RED}Error: This script must be run as root${NC}"
  exit 1
fi

# Parse arguments
if [ "$#" -ne 5 ]; then
    echo "Usage: $0 ROUTER_ID TOKEN RADIUS_SECRET SERVER_IP MAC_ADDRESS"
    echo ""
    echo "Example:"
    echo "  $0 cmhujj1f6000112soujpo0noz e26b8c19afa977... 5d62856936faa... 192.168.42.181 08:00:27:BA:FE:8D"
    exit 1
fi

ROUTER_ID="$1"
TOKEN="$2"
RADIUS_SECRET="$3"
SERVER_IP="$4"
MAC_ADDRESS="$5"

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}SpotFi OpenWRT Router Setup${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Router ID: $ROUTER_ID"
echo "Server IP: $SERVER_IP"
echo "MAC Address: $MAC_ADDRESS"
echo ""

# Step 1: Update package list
echo -e "${YELLOW}[1/9] Updating package list...${NC}"
opkg update

# Step 2: Install required packages
echo -e "${YELLOW}[2/9] Installing required packages...${NC}"
echo "  - Installing CoovaChilli..."
opkg install coova-chilli

echo "  - Installing Python and WebSocket support..."
opkg install python3-light python3-websocket-client

echo -e "${GREEN}✓ Packages installed${NC}"

# Step 3: Configure CoovaChilli
echo -e "${YELLOW}[3/9] Configuring CoovaChilli...${NC}"

# Backup original config
if [ -f /etc/chilli/config ]; then
    cp /etc/chilli/config /etc/chilli/config.backup.$(date +%Y%m%d_%H%M%S)
fi

# Get WAN and LAN interfaces
WAN_IF=$(uci get network.wan.ifname 2>/dev/null || echo "eth1")
WIFI_IF=$(iw dev | grep Interface | awk '{print $2}' | head -n1 || echo "wlan0")

cat > /etc/chilli/config << EOF
# SpotFi CoovaChilli Configuration
# Auto-generated by setup script

# Network Configuration
HS_WANIF=$WAN_IF
HS_LANIF=$WIFI_IF
HS_NETWORK=10.1.0.0
HS_NETMASK=255.255.255.0
HS_UAMLISTEN=10.1.0.1
HS_UAMPORT=3990

# DNS Servers
HS_DNS1=8.8.8.8
HS_DNS2=8.8.4.4

# RADIUS Configuration
HS_RADIUS=$SERVER_IP
HS_RADSECRET=$RADIUS_SECRET
HS_RADAUTH=1812
HS_RADACCT=1813

# NAS Identifier (SpotFi Router ID)
HS_NASID=$ROUTER_ID
HS_NASMAC=$MAC_ADDRESS

# Portal Configuration
HS_UAMSERVER=http://$SERVER_IP:8080/portal
HS_UAMHOMEPAGE=http://www.google.com
HS_UAMSECRET=$(openssl rand -hex 16)

# Allowed domains/IPs
HS_UAMALLOW=$SERVER_IP

# Session settings
HS_DEFIDLETIMEOUT=3600
HS_DEFSESSIONTIMEOUT=0

# Logging
HS_REDIR=on
HS_DEBUG=1
EOF

echo -e "${GREEN}✓ CoovaChilli configured${NC}"

# Step 4: Configure network
echo -e "${YELLOW}[4/9] Configuring network interfaces...${NC}"

# Add hotspot interface if it doesn't exist
if ! uci show network.hotspot >/dev/null 2>&1; then
    uci set network.hotspot=interface
    uci set network.hotspot.proto='static'
    uci set network.hotspot.ipaddr='10.1.0.1'
    uci set network.hotspot.netmask='255.255.255.0'
    uci commit network
fi

echo -e "${GREEN}✓ Network configured${NC}"

# Step 5: Configure WiFi
echo -e "${YELLOW}[5/9] Configuring WiFi...${NC}"

# Get first radio
RADIO=$(uci show wireless | grep "wireless\..*=wifi-device" | head -n1 | cut -d. -f2 | cut -d= -f1)

if [ -n "$RADIO" ]; then
    # Configure radio
    uci set wireless.$RADIO.disabled='0'
    uci set wireless.$RADIO.channel='6'
    
    # Configure interface for hotspot
    IFACE="${RADIO}_spotfi"
    uci set wireless.$IFACE=wifi-iface
    uci set wireless.$IFACE.device="$RADIO"
    uci set wireless.$IFACE.network='hotspot'
    uci set wireless.$IFACE.mode='ap'
    uci set wireless.$IFACE.ssid='SpotFi-Guest'
    uci set wireless.$IFACE.encryption='none'
    
    uci commit wireless
    echo -e "${GREEN}✓ WiFi configured (SSID: SpotFi-Guest)${NC}"
else
    echo -e "${YELLOW}⚠ Could not find WiFi radio, skipping WiFi configuration${NC}"
fi

# Step 6: Configure firewall
echo -e "${YELLOW}[6/9] Configuring firewall...${NC}"

# Add hotspot zone if it doesn't exist
if ! uci show firewall | grep -q "name='hotspot'"; then
    uci add firewall zone
    uci set firewall.@zone[-1].name='hotspot'
    uci set firewall.@zone[-1].input='REJECT'
    uci set firewall.@zone[-1].output='ACCEPT'
    uci set firewall.@zone[-1].forward='REJECT'
    uci set firewall.@zone[-1].network='hotspot'
    
    # Add forwarding from hotspot to wan
    uci add firewall forwarding
    uci set firewall.@forwarding[-1].src='hotspot'
    uci set firewall.@forwarding[-1].dest='wan'
    
    # Allow RADIUS
    uci add firewall rule
    uci set firewall.@rule[-1].name='Allow-RADIUS-Auth'
    uci set firewall.@rule[-1].src='wan'
    uci set firewall.@rule[-1].dest_port='1812'
    uci set firewall.@rule[-1].proto='udp'
    uci set firewall.@rule[-1].target='ACCEPT'
    
    uci add firewall rule
    uci set firewall.@rule[-1].name='Allow-RADIUS-Acct'
    uci set firewall.@rule[-1].src='wan'
    uci set firewall.@rule[-1].dest_port='1813'
    uci set firewall.@rule[-1].proto='udp'
    uci set firewall.@rule[-1].target='ACCEPT'
    
    uci commit firewall
fi

echo -e "${GREEN}✓ Firewall configured${NC}"

# Step 7: Install WebSocket bridge
echo -e "${YELLOW}[7/9] Installing WebSocket bridge...${NC}"

mkdir -p /root/spotfi-bridge

cat > /root/spotfi-bridge/bridge.py << 'PYEOF'
#!/usr/bin/env python3
"""SpotFi WebSocket Bridge for OpenWRT"""

import websocket
import json
import time
import subprocess
import os
import sys

ROUTER_ID = os.getenv('SPOTFI_ROUTER_ID')
TOKEN = os.getenv('SPOTFI_TOKEN')
MAC = os.getenv('SPOTFI_MAC')
WS_URL = os.getenv('SPOTFI_WS_URL')

class SpotFiBridge:
    def __init__(self):
        self.ws = None
        self.running = True
        
    def get_router_metrics(self):
        """Get router metrics"""
        try:
            metrics = {}
            
            # CPU load
            with open('/proc/loadavg', 'r') as f:
                load = f.read().split()[0]
            metrics['cpuLoad'] = float(load) * 100
            
            # Memory
            with open('/proc/meminfo', 'r') as f:
                meminfo = f.read()
                total = int([x for x in meminfo.split('\n') if 'MemTotal' in x][0].split()[1])
                free = int([x for x in meminfo.split('\n') if 'MemFree' in x][0].split()[1])
            metrics['freeMemory'] = free
            metrics['totalMemory'] = total
            
            # Uptime
            with open('/proc/uptime', 'r') as f:
                uptime_seconds = int(float(f.read().split()[0]))
            metrics['uptime'] = str(uptime_seconds)
            
            # Active users
            try:
                result = subprocess.check_output(['chilli_query', 'list'], stderr=subprocess.DEVNULL)
                lines = result.decode().strip().split('\n')
                metrics['activeUsers'] = max(0, len(lines) - 1)
            except:
                metrics['activeUsers'] = 0
            
            return metrics
        except Exception as e:
            print(f"Error getting metrics: {e}", file=sys.stderr)
            return {}
    
    def on_message(self, ws, message):
        try:
            data = json.loads(message)
            msg_type = data.get('type')
            print(f"Received: {msg_type}")
            
            if msg_type == 'command':
                self.handle_command(data.get('command'))
            elif msg_type == 'connected':
                print(f"✓ Registered: {data.get('routerId')}")
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
    
    def handle_command(self, command):
        print(f"Executing: {command}")
        try:
            if command == 'reboot':
                subprocess.run(['reboot'])
            elif command == 'get-status':
                self.send_metrics()
            elif command == 'fetch-logs':
                logs = subprocess.check_output(['logread', '-l', '50']).decode()
                self.send_message({'type': 'logs', 'data': logs})
        except Exception as e:
            print(f"Command failed: {e}", file=sys.stderr)
    
    def on_error(self, ws, error):
        print(f"WebSocket error: {error}", file=sys.stderr)
    
    def on_close(self, ws, close_status_code, close_msg):
        print("WebSocket closed. Reconnecting in 5s...")
        time.sleep(5)
        if self.running:
            self.connect()
    
    def on_open(self, ws):
        print("✓ WebSocket connected")
        self.send_metrics()
    
    def send_message(self, data):
        if self.ws and self.ws.sock and self.ws.sock.connected:
            self.ws.send(json.dumps(data))
    
    def send_metrics(self):
        metrics = self.get_router_metrics()
        if metrics:
            self.send_message({'type': 'metrics', 'metrics': metrics})
    
    def connect(self):
        url = f"{WS_URL}?id={ROUTER_ID}&token={TOKEN}&mac={MAC}"
        print(f"Connecting to {WS_URL}...")
        
        self.ws = websocket.WebSocketApp(
            url,
            on_message=self.on_message,
            on_error=self.on_error,
            on_close=self.on_close,
            on_open=self.on_open
        )
        self.ws.run_forever(ping_interval=60, ping_timeout=10)
    
    def start(self):
        print("SpotFi Bridge starting...")
        print(f"Router ID: {ROUTER_ID}")
        while self.running:
            try:
                self.connect()
            except KeyboardInterrupt:
                self.running = False
            except Exception as e:
                print(f"Error: {e}", file=sys.stderr)
                time.sleep(10)

if __name__ == '__main__':
    bridge = SpotFiBridge()
    bridge.start()
PYEOF

chmod +x /root/spotfi-bridge/bridge.py

# Create environment file
cat > /etc/spotfi.env << EOF
export SPOTFI_ROUTER_ID="$ROUTER_ID"
export SPOTFI_TOKEN="$TOKEN"
export SPOTFI_MAC="$MAC_ADDRESS"
export SPOTFI_WS_URL="ws://$SERVER_IP:8080/ws"
EOF

chmod 600 /etc/spotfi.env

echo -e "${GREEN}✓ WebSocket bridge installed${NC}"

# Step 8: Create init scripts
echo -e "${YELLOW}[8/9] Creating init scripts...${NC}"

cat > /etc/init.d/spotfi-bridge << 'INITEOF'
#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/root/spotfi-bridge/bridge.py

start_service() {
    . /etc/spotfi.env
    
    procd_open_instance
    procd_set_param command /usr/bin/python3 $PROG
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param env SPOTFI_ROUTER_ID="$SPOTFI_ROUTER_ID"
    procd_set_param env SPOTFI_TOKEN="$SPOTFI_TOKEN"
    procd_set_param env SPOTFI_MAC="$SPOTFI_MAC"
    procd_set_param env SPOTFI_WS_URL="$SPOTFI_WS_URL"
    procd_close_instance
}
INITEOF

chmod +x /etc/init.d/spotfi-bridge

echo -e "${GREEN}✓ Init scripts created${NC}"

# Step 9: Enable and start services
echo -e "${YELLOW}[9/9] Starting services...${NC}"

/etc/init.d/chilli enable
/etc/init.d/spotfi-bridge enable

# Restart network
/etc/init.d/network restart
sleep 3

# Restart firewall
/etc/init.d/firewall restart
sleep 2

# Start CoovaChilli
/etc/init.d/chilli restart
sleep 2

# Start WebSocket bridge
/etc/init.d/spotfi-bridge start

echo -e "${GREEN}✓ Services started${NC}"

# Final status check
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Router Status:"
echo "  - Router ID: $ROUTER_ID"
echo "  - Server: $SERVER_IP"
echo "  - WiFi SSID: SpotFi-Guest"
echo "  - Gateway: 10.1.0.1"
echo ""
echo "Verification:"
echo "  1. Check CoovaChilli: /etc/init.d/chilli status"
echo "  2. Check WebSocket: ps | grep bridge.py"
echo "  3. View logs: logread -f"
echo "  4. Check SpotFi dashboard - router should show ONLINE"
echo ""
echo -e "${YELLOW}Note: It may take 30-60 seconds for the router to appear as ONLINE${NC}"
echo ""

